import Aside from '@/components/Aside';
import Header from '@/components/Header';
import Sliderbar from '@/components/Sliderbar';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
const NoSSR = dynamic(() => import('../components/bg'), { ssr: false });
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} relative flex h-screen flex-col items-center justify-start md:w-full lg:px-24 xl:px-32 2xl:px-80`}
      >
        <Script src='//at.alicdn.com/t/c/font_2023298_s3opdq0sy8m.js' />
        <NoSSR />
        <Header />
        <div className='z-10 mt-[1px] flex w-full flex-auto flex-row overflow-hidden'>
          <Aside />
          {children}
          <Sliderbar />
        </div>
      </body>
    </html>
  );
}
